name: 📄 Page request
title: "page request: "
description: Page request template.
labels: new command
body:
  - type: textarea
    attributes:
      label: Command description
      description: Describe a command you want to be summarized.
      placeholder: Tell us about the command!
  - type: input
    attributes:
      label: Command details
      description: Describe any details related to a command.
      placeholder: e.g. command version
  - type: dropdown
    attributes:
      label: OS
      description: Select an operating system category which this command falls into.
      multiple: false
      options:
        - Linux
        - Android
        - macOS
        - Windows
        - Other
        - More than one operating system
    validations:
      required: true
